name: liteagent_sdk_dart
description: A LiteAgent Dart SDK, easy way to access your agent.
version: 0.1.0
repository: https://github.com/LiteVar/LiteAgent/tree/master/lite_agent_sdk/dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  opentool_dart: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.9
  lints: ^5.0.0
  test: ^1.24.0
  dotenv: ^4.2.0
