version: '3.3'

services:
  mongo:
    image: crpi-7i3xk868tuahj8mk.cn-shenzhen.personal.cr.aliyuncs.com/lv_public/mongo:4.4.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=LiteAgent
      - MONGO_INITDB_DATABASE=admin  
    volumes:
      - ./mongo/mongo_data:/data/db
    command: --auth

  redis:
    image: crpi-7i3xk868tuahj8mk.cn-shenzhen.personal.cr.aliyuncs.com/lv_public/redis:6.2.14
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=LiteAgent	  
    command: ["redis-server", "--requirepass", "LiteAgent", "--appendonly", "yes"]
    volumes:
      - ./redis/redis_data:/data

  lite-agent-app:
    image: crpi-7i3xk868tuahj8mk.cn-shenzhen.personal.cr.aliyuncs.com/lv_public/openjdk:17-jdk
    container_name: lite-agent-app
    working_dir: /home/LiteAgent
    volumes:
      - ./LiteAgent/app:/home/LiteAgent/app
      - ./LiteAgent/config:/home/LiteAgent/config
      - ./LiteAgent/logs:/home/LiteAgent/logs
      - ./LiteAgent/file:/home/LiteAgent/file
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:LiteAgent@mongo:27017/lite-agent?authSource=admin
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=true
      - SPRING_DATA_MONGODB_FIELD_NAMING_STRATEGY=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy  
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=LiteAgent
    command: ["java", "-jar", "/home/LiteAgent/app/lite-agent-0.1.0.jar", "--spring.config.location=/home/LiteAgent/config/", "-Dlogback.configurationFile=/home/LiteAgent/config/logback-spring.xml"]
    depends_on:
      - mongo
      - redis
    ports:
      - "8086:8086"

  nginx:
    image: crpi-7i3xk868tuahj8mk.cn-shenzhen.personal.cr.aliyuncs.com/lv_public/nginx:latest
    container_name: lite-agent-web
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - lite-agent-app

  etcd:
    container_name: milvus-etcd
    image: crpi-7i3xk868tuahj8mk.cn-shenzhen.personal.cr.aliyuncs.com/lv_public/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: crpi-7i3xk868tuahj8mk.cn-shenzhen.personal.cr.aliyuncs.com/lv_public/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: crpi-7i3xk868tuahj8mk.cn-shenzhen.personal.cr.aliyuncs.com/lv_public/milvus:v2.5.6
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"