spring:
  data:
    redis:
      host: 192.168.2.188
      port: 6379
      password: Inner@220
      database: 3
mongo-plus:
  data:
    mongodb:
      host: 192.168.2.188
      port: 27017
      database: liteagent-dingtalk-adapter
      username: admin
      password: litevar@admin#mongo
      authentication-database: admin
      connect-timeout-m-s: 50000