server:
  servlet:
    context-path: /liteAgent
  port: 8080
spring:
  application:
    name: liteAgent
  profiles:
    active: local
  mail:
    host: xxxx
    username: xxxx
    password: xxxx
    port: 465
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mongo-plus:
  configuration:
    field:
      camel-to-underline: true
      ignoring-null: false
    auto-create-index: true
    logic:
      open: true
    banner: false
    auto-convert-object-id: false
  log: true
  pretty: true

llm:
  # 大模型请求超时时间(单位:秒)
  timeout: 300

aliyun:
  oss:
    endpoint: oss-cn-placeholder.aliyuncs.com
    custom-domain:
    region: cn-placeholder
    bucket-name: liteagent-placeholder-9x2k
    access-key-id: AKID_PLACEHOLDER_7F2NQ8M4
    access-key-secret: SK_PLACEHOLDER_p3R8vK4m2Lq9xN7z

storage:
  type: local
#  type: oss
  base-path-local: /home/liteAgent/upload
  base-path-oss: private
  image-path: multimedia/image/
  audio-path: multimedia/audio/
  video-path: multimedia/video/
  document-path: document/knowledge/
  access-timeout: 1800 # 30 minutes
