spring:
  data:
    redis:
      database: 6
      host: 127.0.0.1
      port: 6379
      password: xxx

mongo-plus:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27018
      username: xxx
      password: xxx
      authentication-database: admin
      database: lite-agent
      connect-timeout-m-s: 50000

qdrant:
  host: 127.0.0.1
  port: 6334
  use-tls: false
  api-key: xxx
  timeout-seconds: 10

plugin:
  runner:
    base-url: http://127.0.0.1:18080
    encrypted-key: xxx

hub:
  url: http://127.0.0.1:9081
  key: xxx
