// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options, formDataBodySerializer } from '@hey-api/client-fetch';
import type {
  GetV1RegisterPicCaptchaError,
  GetV1RegisterPicCaptchaResponse,
  PostV1RegisterSubmitRegisterEmailData,
  PostV1RegisterSubmitRegisterEmailError,
  PostV1RegisterSubmitRegisterEmailResponse,
  GetV1RegisterVerifyEmailCodeData,
  GetV1RegisterVerifyEmailCodeError,
  GetV1RegisterVerifyEmailCodeResponse,
  PostV1RegisterCompleteRegisterData,
  PostV1RegisterCompleteRegisterError,
  PostV1RegisterCompleteRegisterResponse,
  PostV1AuthLoginData,
  PostV1AuthLoginError,
  PostV1AuthLoginResponse,
  PostV1AuthLoginOfInitData,
  PostV1AuthLoginOfInitError,
  PostV1AuthLoginOfInitResponse,
  GetV1AuthInitStatusError,
  GetV1AuthInitStatusResponse,
  PostV1AuthLogoutData,
  PostV1AuthLogoutError,
  PostV1AuthLogoutResponse,
  GetV1ToolListData,
  GetV1ToolListError,
  GetV1ToolListResponse,
  GetV1ToolDetailByIdData,
  GetV1ToolDetailByIdError,
  GetV1ToolDetailByIdResponse,
  PostV1ToolAddData,
  PostV1ToolAddError,
  PostV1ToolAddResponse,
  PutV1ToolUpdateData,
  PutV1ToolUpdateError,
  PutV1ToolUpdateResponse,
  DeleteV1ToolByIdData,
  DeleteV1ToolByIdError,
  DeleteV1ToolByIdResponse,
  PostV1ToolCheckSchemaData,
  PostV1ToolCheckSchemaError,
  PostV1ToolCheckSchemaResponse,
  GetV1ToolListWithFunctionData,
  GetV1ToolListWithFunctionError,
  GetV1ToolListWithFunctionResponse,
  GetV1ToolLoadOpenToolSchemaData,
  GetV1ToolLoadOpenToolSchemaError,
  GetV1ToolLoadOpenToolSchemaResponse,
  GetV1ToolExportByIdData,
  GetV1ToolExportByIdError,
  GetV1ToolExportByIdResponse,
  PostV1ModelAddData,
  PostV1ModelAddError,
  PostV1ModelAddResponse,
  DeleteV1ModelByIdData,
  DeleteV1ModelByIdError,
  DeleteV1ModelByIdResponse,
  PutV1ModelUpdateData,
  PutV1ModelUpdateError,
  PutV1ModelUpdateResponse,
  GetV1ModelListData,
  GetV1ModelListError,
  GetV1ModelListResponse,
  GetV1ModelProvidersData,
  GetV1ModelProvidersError,
  GetV1ModelProvidersResponse,
  GetV1ModelExportByIdData,
  GetV1ModelExportByIdError,
  GetV1ModelExportByIdResponse,
  PostV1ModelImportData,
  PostV1ModelImportError,
  PostV1ModelImportResponse,
  PostV1ModelAddForSystemData,
  PostV1ModelAddForSystemError,
  PostV1ModelAddForSystemResponse,
  GetV1ModelListForSystemData,
  GetV1ModelListForSystemError,
  GetV1ModelListForSystemResponse,
  DeleteV1ModelDeleteForSystemByIdData,
  DeleteV1ModelDeleteForSystemByIdError,
  DeleteV1ModelDeleteForSystemByIdResponse,
  PutV1ModelUpdateForSystemData,
  PutV1ModelUpdateForSystemError,
  PutV1ModelUpdateForSystemResponse,
  PostV1ModelImportForSystemData,
  PostV1ModelImportForSystemError,
  PostV1ModelImportForSystemResponse,
  PostV1ModelByIdPriceData,
  PostV1ModelByIdPriceError,
  PostV1ModelByIdPriceResponse,
  PostV1ModelByIdStatusToggleData,
  PostV1ModelByIdStatusToggleError,
  PostV1ModelByIdStatusToggleResponse,
  PostV1WorkspaceAddData,
  PostV1WorkspaceAddError,
  PostV1WorkspaceAddResponse,
  GetV1WorkspaceListData,
  GetV1WorkspaceListError,
  GetV1WorkspaceListResponse,
  GetV1WorkspaceMemberListData,
  GetV1WorkspaceMemberListError,
  GetV1WorkspaceMemberListResponse,
  PostV1WorkspaceMemberData,
  PostV1WorkspaceMemberError,
  PostV1WorkspaceMemberResponse,
  DeleteV1WorkspaceMemberByMemberIdData,
  DeleteV1WorkspaceMemberByMemberIdError,
  DeleteV1WorkspaceMemberByMemberIdResponse,
  PutV1WorkspaceMemberByMemberIdData,
  PutV1WorkspaceMemberByMemberIdError,
  PutV1WorkspaceMemberByMemberIdResponse,
  GetV1WorkspaceActivateInfoData,
  GetV1WorkspaceActivateInfoError,
  GetV1WorkspaceActivateInfoResponse,
  PostV1WorkspaceActivateMemberData,
  PostV1WorkspaceActivateMemberError,
  PostV1WorkspaceActivateMemberResponse,
  GetV1AgentByIdData,
  GetV1AgentByIdError,
  GetV1AgentByIdResponse,
  DeleteV1AgentByIdData,
  DeleteV1AgentByIdError,
  DeleteV1AgentByIdResponse,
  PutV1AgentByIdData,
  PutV1AgentByIdError,
  PutV1AgentByIdResponse,
  PostV1AgentAddData,
  PostV1AgentAddError,
  PostV1AgentAddResponse,
  PostV1AgentEnableShareByIdData,
  PostV1AgentEnableShareByIdError,
  PostV1AgentEnableShareByIdResponse,
  GetV1AgentListData,
  GetV1AgentListError,
  GetV1AgentListResponse,
  GetV1AgentAdminListData,
  GetV1AgentAdminListError,
  GetV1AgentAdminListResponse,
  GetV1AgentAdminInfoByIdData,
  GetV1AgentAdminInfoByIdError,
  GetV1AgentAdminInfoByIdResponse,
  PutV1AgentReleaseByIdData,
  PutV1AgentReleaseByIdError,
  PutV1AgentReleaseByIdResponse,
  PostV1AgentGenerateApiKeyByIdData,
  PostV1AgentGenerateApiKeyByIdError,
  PostV1AgentGenerateApiKeyByIdResponse,
  PostV1AgentResetSequenceByAgentIdData,
  PostV1AgentResetSequenceByAgentIdError,
  PostV1AgentResetSequenceByAgentIdResponse,
  GetV1AgentExportByIdData,
  GetV1AgentExportByIdError,
  GetV1AgentExportByIdResponse,
  PostV1AgentImportPreviewData,
  PostV1AgentImportPreviewError,
  PostV1AgentImportPreviewResponse,
  PostV1AgentImportByTokenData,
  PostV1AgentImportByTokenError,
  PostV1AgentImportByTokenResponse,
  GetV1AgentImportProgressByTokenData,
  GetV1AgentImportProgressByTokenError,
  GetV1AgentImportProgressByTokenResponse,
  GetV1AgentImportPreviewFromDownloadData,
  GetV1AgentImportPreviewFromDownloadError,
  GetV1AgentImportPreviewFromDownloadResponse,
  GetV1ChatStreamData,
  GetV1ChatStreamError,
  GetV1ChatStreamResponse,
  PostV1ChatInitSessionByAgentIdData,
  PostV1ChatInitSessionByAgentIdError,
  PostV1ChatInitSessionByAgentIdResponse,
  PostV1ChatInitSessionData,
  PostV1ChatInitSessionError,
  PostV1ChatInitSessionResponse,
  GetV1ChatRecentAgentData,
  GetV1ChatRecentAgentError,
  GetV1ChatRecentAgentResponse,
  GetV1ChatAgentChatByAgentIdData,
  GetV1ChatAgentChatByAgentIdError,
  GetV1ChatAgentChatByAgentIdResponse,
  PostV1ChatSendBySessionIdData,
  PostV1ChatSendBySessionIdError,
  PostV1ChatSendBySessionIdResponse,
  PostV1ChatClearSessionData,
  PostV1ChatClearSessionError,
  PostV1ChatClearSessionResponse,
  PostV1ChatClearDebugRecordData,
  PostV1ChatClearDebugRecordError,
  PostV1ChatClearDebugRecordResponse,
  PostV1ChatAudioTranscriptionsData,
  PostV1ChatAudioTranscriptionsError,
  PostV1ChatAudioTranscriptionsResponse,
  PostV1ChatAudioSpeechData,
  PostV1ChatAudioSpeechError,
  PostV1ChatAudioSpeechResponse,
  GetV1ChatAgentChatData,
  GetV1ChatAgentChatError,
  GetV1ChatAgentChatResponse,
  PostV1ChatStreamBySessionIdData,
  PostV1ChatStreamBySessionIdError,
  PostV1ChatStreamBySessionIdResponse,
  PostV1ChatStopData,
  PostV1ChatStopError,
  PostV1ChatStopResponse,
  PostV1ChatAudioTranscriptionsStreamData,
  PostV1ChatAudioTranscriptionsStreamError,
  PostV1ChatAudioTranscriptionsStreamResponse,
  PostV1ChatAudioSpeechStreamData,
  PostV1ChatAudioSpeechStreamError,
  PostV1ChatAudioSpeechStreamResponse,
  GetV1UserInfoData,
  GetV1UserInfoError,
  GetV1UserInfoResponse,
  PutV1UserUpdateData,
  PutV1UserUpdateError,
  PutV1UserUpdateResponse,
  PutV1UserUpdatePwdData,
  PutV1UserUpdatePwdError,
  PutV1UserUpdatePwdResponse,
  PostV1UserResetPwdCaptchaData,
  PostV1UserResetPwdCaptchaError,
  PostV1UserResetPwdCaptchaResponse,
  PostV1UserResetPwdCaptchaVerifyData,
  PostV1UserResetPwdCaptchaVerifyError,
  PostV1UserResetPwdCaptchaVerifyResponse,
  GetV1UserResetPwdByUuidData,
  GetV1UserResetPwdByUuidError,
  GetV1UserResetPwdByUuidResponse,
  PostV1UserResetPwdByUuidData,
  PostV1UserResetPwdByUuidError,
  PostV1UserResetPwdByUuidResponse,
  PostV1UserResetPwdConfirmData,
  PostV1UserResetPwdConfirmError,
  PostV1UserResetPwdConfirmResponse,
  PostV1FileUploadData,
  PostV1FileUploadError,
  PostV1FileUploadResponse,
  GetV1FileDownloadData,
  GetV1FileDownloadError,
  GetV1FileDownloadResponse,
  PostV1FileDatasetUploadData,
  PostV1FileDatasetUploadError,
  PostV1FileDatasetUploadResponse,
  GetV1FileDatasetFileDownloadData,
  GetV1FileDatasetFileDownloadError,
  GetV1FileDatasetFileDownloadResponse,
  GetV1FileDatasetMarkdownDownloadData,
  GetV1FileDatasetMarkdownDownloadError,
  GetV1FileDatasetMarkdownDownloadResponse,
  GetV1FileDatasetMarkdownProgressData,
  GetV1FileDatasetMarkdownProgressError,
  GetV1FileDatasetMarkdownProgressResponse,
  GetV1FileDatasetMarkdownPreviewData,
  GetV1FileDatasetMarkdownPreviewError,
  GetV1FileDatasetMarkdownPreviewResponse,
  GetV1FileDatasetImagesByFilenameData,
  GetV1FileDatasetImagesByFilenameError,
  GetV1FileDatasetImagesByFilenameResponse,
  DeleteV1FileByIdData,
  DeleteV1FileByIdError,
  DeleteV1FileByIdResponse,
  GetV1FileDatasetImagesByFileIdByFilenameData,
  GetV1FileDatasetImagesByFileIdByFilenameError,
  GetV1FileDatasetImagesByFileIdByFilenameResponse,
  PostV1FileChatUploadData,
  PostV1FileChatUploadError,
  PostV1FileChatUploadResponse,
  GetV1FileResourceGenerateUrlData,
  GetV1FileResourceGenerateUrlError,
  GetV1FileResourceGenerateUrlResponse,
  GetV1FileResourceDownloadData,
  GetV1FileResourceDownloadError,
  GetV1FileResourceDownloadResponse,
  PostV1DatasetAddData,
  PostV1DatasetAddError,
  PostV1DatasetAddResponse,
  GetV1DatasetByIdData,
  GetV1DatasetByIdError,
  GetV1DatasetByIdResponse,
  PutV1DatasetByIdData,
  PutV1DatasetByIdError,
  PutV1DatasetByIdResponse,
  DeleteV1DatasetByIdData,
  DeleteV1DatasetByIdError,
  DeleteV1DatasetByIdResponse,
  GetV1DatasetListDatasetsByAgentData,
  GetV1DatasetListDatasetsByAgentError,
  GetV1DatasetListDatasetsByAgentResponse,
  PutV1DatasetByIdShareData,
  PutV1DatasetByIdShareError,
  PutV1DatasetByIdShareResponse,
  GetV1DatasetByIdRetrieveHistoryData,
  GetV1DatasetByIdRetrieveHistoryError,
  GetV1DatasetByIdRetrieveHistoryResponse,
  PostV1DatasetByDatasetIdDocumentsData,
  PostV1DatasetByDatasetIdDocumentsError,
  PostV1DatasetByDatasetIdDocumentsResponse,
  GetV1DatasetByDatasetIdDocumentsData,
  GetV1DatasetByDatasetIdDocumentsError,
  GetV1DatasetByDatasetIdDocumentsResponse,
  PutV1DatasetDocumentsByDocumentIdRenameData,
  PutV1DatasetDocumentsByDocumentIdRenameError,
  PutV1DatasetDocumentsByDocumentIdRenameResponse,
  DeleteV1DatasetDocumentsByDocumentIdData,
  DeleteV1DatasetDocumentsByDocumentIdError,
  DeleteV1DatasetDocumentsByDocumentIdResponse,
  DeleteV1DatasetDocumentsBatchDeleteData,
  DeleteV1DatasetDocumentsBatchDeleteError,
  DeleteV1DatasetDocumentsBatchDeleteResponse,
  GetV1DatasetDocumentsByDocumentIdSegmentsData,
  GetV1DatasetDocumentsByDocumentIdSegmentsError,
  GetV1DatasetDocumentsByDocumentIdSegmentsResponse,
  PostV1DatasetDocumentsByDocumentIdSegmentsData,
  PostV1DatasetDocumentsByDocumentIdSegmentsError,
  PostV1DatasetDocumentsByDocumentIdSegmentsResponse,
  PutV1DatasetDocumentsByDocumentIdEnableData,
  PutV1DatasetDocumentsByDocumentIdEnableError,
  PutV1DatasetDocumentsByDocumentIdEnableResponse,
  PutV1DatasetSegmentsBySegmentIdEnableData,
  PutV1DatasetSegmentsBySegmentIdEnableError,
  PutV1DatasetSegmentsBySegmentIdEnableResponse,
  GetV1DatasetDocumentsByDocumentIdSegmentsSearchByTextData,
  GetV1DatasetDocumentsByDocumentIdSegmentsSearchByTextError,
  GetV1DatasetDocumentsByDocumentIdSegmentsSearchByTextResponse,
  PutV1DatasetSegmentsBySegmentIdData,
  PutV1DatasetSegmentsBySegmentIdError,
  PutV1DatasetSegmentsBySegmentIdResponse,
  DeleteV1DatasetSegmentsBySegmentIdData,
  DeleteV1DatasetSegmentsBySegmentIdError,
  DeleteV1DatasetSegmentsBySegmentIdResponse,
  GetV1DatasetByIdRetrieveData,
  GetV1DatasetByIdRetrieveError,
  GetV1DatasetByIdRetrieveResponse,
  GetV1DatasetByIdApiKeyGenerateData,
  GetV1DatasetByIdApiKeyGenerateError,
  GetV1DatasetByIdApiKeyGenerateResponse,
  PostV1DatasetDocumentsSplitData,
  PostV1DatasetDocumentsSplitError,
  PostV1DatasetDocumentsSplitResponse,
  DeleteV1DatasetSegmentsBatchDeleteData,
  DeleteV1DatasetSegmentsBatchDeleteError,
  DeleteV1DatasetSegmentsBatchDeleteResponse,
  GetV1DatasetListData,
  GetV1DatasetListError,
  GetV1DatasetListResponse,
  GetV1DatasetByIdRetrieveExternalData,
  GetV1DatasetByIdRetrieveExternalError,
  GetV1DatasetByIdRetrieveExternalResponse,
  GetV1DatasetRetrieveHistoryByIdData,
  GetV1DatasetRetrieveHistoryByIdError,
  GetV1DatasetRetrieveHistoryByIdResponse,
  GetV1DatasetRetrieveDesktopData,
  GetV1DatasetRetrieveDesktopError,
  GetV1DatasetRetrieveDesktopResponse,
  PutV1DatasetDocumentSummaryData,
  PutV1DatasetDocumentSummaryError,
  PutV1DatasetDocumentSummaryResponse,
  GetV1DatasetDocumentsByDocumentIdSummaryData,
  GetV1DatasetDocumentsByDocumentIdSummaryError,
  GetV1DatasetDocumentsByDocumentIdSummaryResponse,
  GetV1DatasetDocumentsInfoByDocumentIdData,
  GetV1DatasetDocumentsInfoByDocumentIdError,
  GetV1DatasetDocumentsInfoByDocumentIdResponse,
  GetV1PointsRechargesData,
  GetV1PointsRechargesError,
  GetV1PointsRechargesResponse,
  GetV1PointsUsagesData,
  GetV1PointsUsagesError,
  GetV1PointsUsagesResponse,
  GetV1PointsBalanceData,
  GetV1PointsBalanceError,
  GetV1PointsBalanceResponse,
  GetV1PointsStrategyData,
  GetV1PointsStrategyError,
  GetV1PointsStrategyResponse,
  PutV1PointsStrategyData,
  PutV1PointsStrategyError,
  PutV1PointsStrategyResponse,
  GetV1PointsActiveActivitiesData,
  GetV1PointsActiveActivitiesError,
  GetV1PointsActiveActivitiesResponse,
  GetV1PointsCalculateDiscountData,
  GetV1PointsCalculateDiscountError,
  GetV1PointsCalculateDiscountResponse,
  GetV1RegisterHasBindData,
  GetV1RegisterHasBindError,
  GetV1RegisterHasBindResponse,
  PostV1RegisterSendSmsData,
  PostV1RegisterSendSmsError,
  PostV1RegisterSendSmsResponse,
  PostV1RegisterVerifyCodeData,
  PostV1RegisterVerifyCodeError,
  PostV1RegisterVerifyCodeResponse,
  PostV1RegisterBindData,
  PostV1RegisterBindError,
  PostV1RegisterBindResponse,
  PostV1RegisterRebindData,
  PostV1RegisterRebindError,
  PostV1RegisterRebindResponse,
  GetV1PayPaymentByIdData,
  GetV1PayPaymentByIdError,
  GetV1PayPaymentByIdResponse,
  PostV1PayWechatNativeData,
  PostV1PayWechatNativeError,
  PostV1PayWechatNativeResponse,
  PostV1PayAlipayWebData,
  PostV1PayAlipayWebError,
  PostV1PayAlipayWebResponse,
  GetV1PayPaymentsData,
  GetV1PayPaymentsError,
  GetV1PayPaymentsResponse,
  GetV1PayInvoiceAmountData,
  GetV1PayInvoiceAmountError,
  GetV1PayInvoiceAmountResponse,
  PostV1PayInvoiceApplyData,
  PostV1PayInvoiceApplyError,
  PostV1PayInvoiceApplyResponse,
  GetV1PayInvoiceListData,
  GetV1PayInvoiceListError,
  GetV1PayInvoiceListResponse,
  PostV1PayCloseOrderData,
  PostV1PayCloseOrderError,
  PostV1PayCloseOrderResponse,
  GetV1PluginListData,
  GetV1PluginListError,
  GetV1PluginListResponse,
  PostV1PluginAddData,
  PostV1PluginAddError,
  PostV1PluginAddResponse,
  PutV1PluginByIdData,
  PutV1PluginByIdError,
  PutV1PluginByIdResponse,
  DeleteV1PluginByIdData,
  DeleteV1PluginByIdError,
  DeleteV1PluginByIdResponse,
  PostV1PluginByIdEnableData,
  PostV1PluginByIdEnableError,
  PostV1PluginByIdEnableResponse,
  PostV1PluginByIdDisableData,
  PostV1PluginByIdDisableError,
  PostV1PluginByIdDisableResponse,
  GetV1PluginConnectorData,
  GetV1PluginConnectorError,
  GetV1PluginConnectorResponse,
  PostV1PluginConnectorData,
  PostV1PluginConnectorError,
  PostV1PluginConnectorResponse,
  PutV1PluginConnectorByIdData,
  PutV1PluginConnectorByIdError,
  PutV1PluginConnectorByIdResponse,
  DeleteV1PluginConnectorByIdData,
  DeleteV1PluginConnectorByIdError,
  DeleteV1PluginConnectorByIdResponse,
  GetV1PluginByPluginIdSchemaData,
  GetV1PluginByPluginIdSchemaError,
  GetV1PluginByPluginIdSchemaResponse,
  GetV1PluginConnectorByIdDataData,
  GetV1PluginConnectorByIdDataError,
  GetV1PluginConnectorByIdDataResponse,
  PostV1PluginConnectorByIdStatusData,
  PostV1PluginConnectorByIdStatusError,
  PostV1PluginConnectorByIdStatusResponse,
  PostV1PluginConnectorAnalyzeData,
  PostV1PluginConnectorAnalyzeError,
  PostV1PluginConnectorAnalyzeResponse,
  GetV1PluginAgentListData,
  GetV1PluginAgentListError,
  GetV1PluginAgentListResponse,
  PostV2FileUploadData,
  PostV2FileUploadError,
  PostV2FileUploadResponse,
  GetV2FilePreviewData,
  GetV2FilePreviewError,
  GetV2FilePreviewResponse,
  DeleteV2FileByIdData,
  DeleteV2FileByIdError,
  DeleteV2FileByIdResponse,
  GetV2FileDownloadData,
  GetV2FileDownloadError,
  GetV2FileDownloadResponse,
  GetV2FileDownloadMarkdownData,
  GetV2FileDownloadMarkdownError,
  GetV2FileDownloadMarkdownResponse,
  GetV2FileMarkdownProgressData,
  GetV2FileMarkdownProgressError,
  GetV2FileMarkdownProgressResponse,
  GetV2FileMarkdownPreviewData,
  GetV2FileMarkdownPreviewError,
  GetV2FileMarkdownPreviewResponse,
  PostV1NotifyMockNotifyData,
  PostV1NotifyMockNotifyError,
  PostV1NotifyMockNotifyResponse,
} from './types.gen';

export const client = createClient(createConfig());

/**
 * 1.生成图形验证码
 * <p>有效时间:15分钟</p>
 */
export const getV1RegisterPicCaptcha = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1RegisterPicCaptchaResponse,
    GetV1RegisterPicCaptchaError
  >({
    ...options,
    url: '/v1/register/picCaptcha',
  });
};

/**
 * 2.邮箱注册提交
 * 验证通过会向邮箱发送验证码
 */
export const postV1RegisterSubmitRegisterEmail = <ThrowOnError extends boolean = false>(
  options: Options<PostV1RegisterSubmitRegisterEmailData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1RegisterSubmitRegisterEmailResponse,
    PostV1RegisterSubmitRegisterEmailError
  >({
    ...options,
    url: '/v1/register/submitRegisterEmail',
  });
};

/**
 * 3.验证邮箱验证码是否正确
 */
export const getV1RegisterVerifyEmailCode = <ThrowOnError extends boolean = false>(
  options: Options<GetV1RegisterVerifyEmailCodeData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1RegisterVerifyEmailCodeResponse,
    GetV1RegisterVerifyEmailCodeError
  >({
    ...options,
    url: '/v1/register/verifyEmailCode',
  });
};

/**
 * 4.完成邮箱注册
 */
export const postV1RegisterCompleteRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostV1RegisterCompleteRegisterData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1RegisterCompleteRegisterResponse,
    PostV1RegisterCompleteRegisterError
  >({
    ...options,
    url: '/v1/register/completeRegister',
  });
};

/**
 * 登录
 */
export const postV1AuthLogin = <ThrowOnError extends boolean = false>(
  options: Options<PostV1AuthLoginData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1AuthLoginResponse, PostV1AuthLoginError>({
    ...options,
    url: '/v1/auth/login',
  });
};

/**
 * 初始化系统的登录
 */
export const postV1AuthLoginOfInit = <ThrowOnError extends boolean = false>(
  options: Options<PostV1AuthLoginOfInitData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1AuthLoginOfInitResponse,
    PostV1AuthLoginOfInitError
  >({
    ...options,
    url: '/v1/auth/loginOfInit',
  });
};

/**
 * 系统初始化状态
 * 1-已初始化,0-未初始化
 */
export const getV1AuthInitStatus = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1AuthInitStatusResponse, GetV1AuthInitStatusError>(
    {
      ...options,
      url: '/v1/auth/initStatus',
    }
  );
};

/**
 * 退出登录
 */
export const postV1AuthLogout = <ThrowOnError extends boolean = false>(
  options: Options<PostV1AuthLogoutData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1AuthLogoutResponse, PostV1AuthLogoutError>({
    ...options,
    url: '/v1/auth/logout',
  });
};

/**
 * 工具列表
 */
export const getV1ToolList = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ToolListData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1ToolListResponse, GetV1ToolListError>({
    ...options,
    url: '/v1/tool/list',
  });
};

/**
 * 工具详细信息
 */
export const getV1ToolDetailById = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ToolDetailByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1ToolDetailByIdResponse, GetV1ToolDetailByIdError>(
    {
      ...options,
      url: '/v1/tool/detail/{id}',
    }
  );
};

/**
 * 新增工具
 */
export const postV1ToolAdd = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ToolAddData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1ToolAddResponse, PostV1ToolAddError>({
    ...options,
    url: '/v1/tool/add',
  });
};

/**
 * 修改工具
 */
export const putV1ToolUpdate = <ThrowOnError extends boolean = false>(
  options: Options<PutV1ToolUpdateData, ThrowOnError>
) => {
  return (options?.client ?? client).put<ThrowOnError, PutV1ToolUpdateResponse, PutV1ToolUpdateError>({
    ...options,
    url: '/v1/tool/update',
  });
};

/**
 * 删除工具
 */
export const deleteV1ToolById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1ToolByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<ThrowOnError, DeleteV1ToolByIdResponse, DeleteV1ToolByIdError>({
    ...options,
    url: '/v1/tool/{id}',
  });
};

/**
 * 检查工具schema是否有效
 */
export const postV1ToolCheckSchema = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ToolCheckSchemaData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ToolCheckSchemaResponse,
    PostV1ToolCheckSchemaError
  >({
    ...options,
    url: '/v1/tool/checkSchema',
  });
};

/**
 * 工具列表(带function)
 */
export const getV1ToolListWithFunction = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ToolListWithFunctionData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1ToolListWithFunctionResponse,
    GetV1ToolListWithFunctionError
  >({
    ...options,
    url: '/v1/tool/listWithFunction',
  });
};

/**
 * 获取openTool schema
 */
export const getV1ToolLoadOpenToolSchema = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ToolLoadOpenToolSchemaData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1ToolLoadOpenToolSchemaResponse,
    GetV1ToolLoadOpenToolSchemaError
  >({
    ...options,
    url: '/v1/tool/loadOpenToolSchema',
  });
};

/**
 * 导出工具配置
 */
export const getV1ToolExportById = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ToolExportByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1ToolExportByIdResponse, GetV1ToolExportByIdError>(
    {
      ...options,
      url: '/v1/tool/export/{id}',
    }
  );
};

/**
 * 新建模型
 */
export const postV1ModelAdd = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ModelAddData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1ModelAddResponse, PostV1ModelAddError>({
    ...options,
    url: '/v1/model/add',
  });
};

/**
 * 删除模型
 */
export const deleteV1ModelById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1ModelByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<ThrowOnError, DeleteV1ModelByIdResponse, DeleteV1ModelByIdError>({
    ...options,
    url: '/v1/model/{id}',
  });
};

/**
 * 修改模型
 */
export const putV1ModelUpdate = <ThrowOnError extends boolean = false>(
  options: Options<PutV1ModelUpdateData, ThrowOnError>
) => {
  return (options?.client ?? client).put<ThrowOnError, PutV1ModelUpdateResponse, PutV1ModelUpdateError>({
    ...options,
    url: '/v1/model/update',
  });
};

/**
 * 模型列表
 */
export const getV1ModelList = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ModelListData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1ModelListResponse, GetV1ModelListError>({
    ...options,
    url: '/v1/model/list',
  });
};

/**
 * 模型厂商列表
 */
export const getV1ModelProviders = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ModelProvidersData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1ModelProvidersResponse, GetV1ModelProvidersError>(
    {
      ...options,
      url: '/v1/model/providers',
    }
  );
};

/**
 * 导出模型配置
 */
export const getV1ModelExportById = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ModelExportByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1ModelExportByIdResponse,
    GetV1ModelExportByIdError
  >({
    ...options,
    url: '/v1/model/export/{id}',
  });
};

/**
 * 导入模型配置
 */
export const postV1ModelImport = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ModelImportData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1ModelImportResponse, PostV1ModelImportError>({
    ...options,
    ...formDataBodySerializer,
    headers: {
      'Content-Type': null,
    },
    url: '/v1/model/import',
  });
};

/**
 * 新建模型(系统管理员)
 */
export const postV1ModelAddForSystem = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ModelAddForSystemData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ModelAddForSystemResponse,
    PostV1ModelAddForSystemError
  >({
    ...options,
    url: '/v1/model/addForSystem',
  });
};

/**
 * 模型列表(系统管理员)
 */
export const getV1ModelListForSystem = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ModelListForSystemData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1ModelListForSystemResponse,
    GetV1ModelListForSystemError
  >({
    ...options,
    url: '/v1/model/listForSystem',
  });
};

/**
 * 删除模型(系统管理员)
 */
export const deleteV1ModelDeleteForSystemById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1ModelDeleteForSystemByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteV1ModelDeleteForSystemByIdResponse,
    DeleteV1ModelDeleteForSystemByIdError
  >({
    ...options,
    url: '/v1/model/deleteForSystem/{id}',
  });
};

/**
 * 修改模型(系统管理员)
 */
export const putV1ModelUpdateForSystem = <ThrowOnError extends boolean = false>(
  options: Options<PutV1ModelUpdateForSystemData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    PutV1ModelUpdateForSystemResponse,
    PutV1ModelUpdateForSystemError
  >({
    ...options,
    url: '/v1/model/updateForSystem',
  });
};

/**
 * 导入模型配置(系统管理员)
 */
export const postV1ModelImportForSystem = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ModelImportForSystemData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ModelImportForSystemResponse,
    PostV1ModelImportForSystemError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      'Content-Type': null,
    },
    url: '/v1/model/importForSystem',
  });
};

/**
 * 设置模型定价
 */
export const postV1ModelByIdPrice = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ModelByIdPriceData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ModelByIdPriceResponse,
    PostV1ModelByIdPriceError
  >({
    ...options,
    url: '/v1/model/{id}/price',
  });
};

/**
 * 切换模型状态(启用/禁用)
 */
export const postV1ModelByIdStatusToggle = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ModelByIdStatusToggleData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ModelByIdStatusToggleResponse,
    PostV1ModelByIdStatusToggleError
  >({
    ...options,
    url: '/v1/model/{id}/status/toggle',
  });
};

/**
 * 创建工作空间
 */
export const postV1WorkspaceAdd = <ThrowOnError extends boolean = false>(
  options: Options<PostV1WorkspaceAddData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1WorkspaceAddResponse, PostV1WorkspaceAddError>({
    ...options,
    url: '/v1/workspace/add',
  });
};

/**
 * 当前账号加入的工作空间
 */
export const getV1WorkspaceList = <ThrowOnError extends boolean = false>(
  options: Options<GetV1WorkspaceListData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1WorkspaceListResponse, GetV1WorkspaceListError>({
    ...options,
    url: '/v1/workspace/list',
  });
};

/**
 * 工作空间的成员列表
 */
export const getV1WorkspaceMemberList = <ThrowOnError extends boolean = false>(
  options: Options<GetV1WorkspaceMemberListData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1WorkspaceMemberListResponse,
    GetV1WorkspaceMemberListError
  >({
    ...options,
    url: '/v1/workspace/memberList',
  });
};

/**
 * 新增工作空间成员
 */
export const postV1WorkspaceMember = <ThrowOnError extends boolean = false>(
  options: Options<PostV1WorkspaceMemberData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1WorkspaceMemberResponse,
    PostV1WorkspaceMemberError
  >({
    ...options,
    url: '/v1/workspace/member',
  });
};

/**
 * 删除工作空间成员
 */
export const deleteV1WorkspaceMemberByMemberId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1WorkspaceMemberByMemberIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteV1WorkspaceMemberByMemberIdResponse,
    DeleteV1WorkspaceMemberByMemberIdError
  >({
    ...options,
    url: '/v1/workspace/member/{memberId}',
  });
};

/**
 * 修改成员角色
 */
export const putV1WorkspaceMemberByMemberId = <ThrowOnError extends boolean = false>(
  options: Options<PutV1WorkspaceMemberByMemberIdData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    PutV1WorkspaceMemberByMemberIdResponse,
    PutV1WorkspaceMemberByMemberIdError
  >({
    ...options,
    url: '/v1/workspace/member/{memberId}',
  });
};

/**
 * 获取激活信息
 */
export const getV1WorkspaceActivateInfo = <ThrowOnError extends boolean = false>(
  options: Options<GetV1WorkspaceActivateInfoData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1WorkspaceActivateInfoResponse,
    GetV1WorkspaceActivateInfoError
  >({
    ...options,
    url: '/v1/workspace/activateInfo',
  });
};

/**
 * 通过激活链接加入(登录)
 */
export const postV1WorkspaceActivateMember = <ThrowOnError extends boolean = false>(
  options: Options<PostV1WorkspaceActivateMemberData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1WorkspaceActivateMemberResponse,
    PostV1WorkspaceActivateMemberError
  >({
    ...options,
    url: '/v1/workspace/activateMember',
  });
};

/**
 * agent详情
 */
export const getV1AgentById = <ThrowOnError extends boolean = false>(
  options: Options<GetV1AgentByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1AgentByIdResponse, GetV1AgentByIdError>({
    ...options,
    url: '/v1/agent/{id}',
  });
};

/**
 * 删除agent
 */
export const deleteV1AgentById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1AgentByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<ThrowOnError, DeleteV1AgentByIdResponse, DeleteV1AgentByIdError>({
    ...options,
    url: '/v1/agent/{id}',
  });
};

/**
 * 修改agent
 */
export const putV1AgentById = <ThrowOnError extends boolean = false>(
  options: Options<PutV1AgentByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).put<ThrowOnError, PutV1AgentByIdResponse, PutV1AgentByIdError>({
    ...options,
    url: '/v1/agent/{id}',
  });
};

/**
 * 新建agent
 */
export const postV1AgentAdd = <ThrowOnError extends boolean = false>(
  options: Options<PostV1AgentAddData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1AgentAddResponse, PostV1AgentAddError>({
    ...options,
    url: '/v1/agent/add',
  });
};

/**
 * 开启或关闭分享状态
 */
export const postV1AgentEnableShareById = <ThrowOnError extends boolean = false>(
  options: Options<PostV1AgentEnableShareByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1AgentEnableShareByIdResponse,
    PostV1AgentEnableShareByIdError
  >({
    ...options,
    url: '/v1/agent/enableShare/{id}',
  });
};

/**
 * agent列表
 */
export const getV1AgentList = <ThrowOnError extends boolean = false>(
  options: Options<GetV1AgentListData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1AgentListResponse, GetV1AgentListError>({
    ...options,
    url: '/v1/agent/list',
  });
};

/**
 * agent列表(管理)
 */
export const getV1AgentAdminList = <ThrowOnError extends boolean = false>(
  options: Options<GetV1AgentAdminListData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1AgentAdminListResponse, GetV1AgentAdminListError>(
    {
      ...options,
      url: '/v1/agent/adminList',
    }
  );
};

/**
 * agent详情(管理)
 */
export const getV1AgentAdminInfoById = <ThrowOnError extends boolean = false>(
  options: Options<GetV1AgentAdminInfoByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1AgentAdminInfoByIdResponse,
    GetV1AgentAdminInfoByIdError
  >({
    ...options,
    url: '/v1/agent/adminInfo/{id}',
  });
};

/**
 * 发布
 */
export const putV1AgentReleaseById = <ThrowOnError extends boolean = false>(
  options: Options<PutV1AgentReleaseByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    PutV1AgentReleaseByIdResponse,
    PutV1AgentReleaseByIdError
  >({
    ...options,
    url: '/v1/agent/release/{id}',
  });
};

/**
 * 生成agent ApiKey
 */
export const postV1AgentGenerateApiKeyById = <ThrowOnError extends boolean = false>(
  options: Options<PostV1AgentGenerateApiKeyByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1AgentGenerateApiKeyByIdResponse,
    PostV1AgentGenerateApiKeyByIdError
  >({
    ...options,
    url: '/v1/agent/generateApiKey/{id}',
  });
};

/**
 * 重置方法序列
 */
export const postV1AgentResetSequenceByAgentId = <ThrowOnError extends boolean = false>(
  options: Options<PostV1AgentResetSequenceByAgentIdData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1AgentResetSequenceByAgentIdResponse,
    PostV1AgentResetSequenceByAgentIdError
  >({
    ...options,
    url: '/v1/agent/resetSequence/{agentId}',
  });
};

/**
 * 导出agent
 */
export const getV1AgentExportById = <ThrowOnError extends boolean = false>(
  options: Options<GetV1AgentExportByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1AgentExportByIdResponse,
    GetV1AgentExportByIdError
  >({
    ...options,
    url: '/v1/agent/export/{id}',
  });
};

/**
 * 上传agent文件
 * 读取agent文件返回预览数据供用户确认
 */
export const postV1AgentImportPreview = <ThrowOnError extends boolean = false>(
  options: Options<PostV1AgentImportPreviewData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1AgentImportPreviewResponse,
    PostV1AgentImportPreviewError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      'Content-Type': null,
    },
    url: '/v1/agent/import/preview',
  });
};

/**
 * 导入agent
 */
export const postV1AgentImportByToken = <ThrowOnError extends boolean = false>(
  options: Options<PostV1AgentImportByTokenData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1AgentImportByTokenResponse,
    PostV1AgentImportByTokenError
  >({
    ...options,
    url: '/v1/agent/import/{token}',
  });
};

/**
 * agent 导入进度
 */
export const getV1AgentImportProgressByToken = <ThrowOnError extends boolean = false>(
  options: Options<GetV1AgentImportProgressByTokenData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1AgentImportProgressByTokenResponse,
    GetV1AgentImportProgressByTokenError
  >({
    ...options,
    url: '/v1/agent/import/progress/{token}',
  });
};

/**
 * 一键运行导入agent
 */
export const getV1AgentImportPreviewFromDownload = <ThrowOnError extends boolean = false>(
  options: Options<GetV1AgentImportPreviewFromDownloadData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1AgentImportPreviewFromDownloadResponse,
    GetV1AgentImportPreviewFromDownloadError
  >({
    ...options,
    url: '/v1/agent/import/previewFromDownload',
  });
};

/**
 * @deprecated
 * chat
 */
export const getV1ChatStream = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ChatStreamData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1ChatStreamResponse, GetV1ChatStreamError>({
    ...options,
    url: '/v1/chat/stream',
  });
};

/**
 * 初始化会话
 */
export const postV1ChatInitSessionByAgentId = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ChatInitSessionByAgentIdData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ChatInitSessionByAgentIdResponse,
    PostV1ChatInitSessionByAgentIdError
  >({
    ...options,
    url: '/v1/chat/initSession/{agentId}',
  });
};

/**
 * 初始化会话
 * <strong>适用于调试</strong>
 */
export const postV1ChatInitSession = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ChatInitSessionData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ChatInitSessionResponse,
    PostV1ChatInitSessionError
  >({
    ...options,
    url: '/v1/chat/initSession',
  });
};

/**
 * 最近聊天的agent
 */
export const getV1ChatRecentAgent = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ChatRecentAgentData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1ChatRecentAgentResponse,
    GetV1ChatRecentAgentError
  >({
    ...options,
    url: '/v1/chat/recentAgent',
  });
};

/**
 * agent聊天记录
 */
export const getV1ChatAgentChatByAgentId = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ChatAgentChatByAgentIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1ChatAgentChatByAgentIdResponse,
    GetV1ChatAgentChatByAgentIdError
  >({
    ...options,
    url: '/v1/chat/agentChat/{agentId}',
  });
};

/**
 * @deprecated
 * 发送会话消息
 */
export const postV1ChatSendBySessionId = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ChatSendBySessionIdData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ChatSendBySessionIdResponse,
    PostV1ChatSendBySessionIdError
  >({
    ...options,
    url: '/v1/chat/send/{sessionId}',
  });
};

/**
 * 清空会话信息
 * 退出agent界面时调用,清空上下文时调用
 */
export const postV1ChatClearSession = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ChatClearSessionData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ChatClearSessionResponse,
    PostV1ChatClearSessionError
  >({
    ...options,
    url: '/v1/chat/clearSession',
  });
};

/**
 * 清空聊天记录
 */
export const postV1ChatClearDebugRecord = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ChatClearDebugRecordData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ChatClearDebugRecordResponse,
    PostV1ChatClearDebugRecordError
  >({
    ...options,
    url: '/v1/chat/clearDebugRecord',
  });
};

/**
 * 音频转文字
 */
export const postV1ChatAudioTranscriptions = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ChatAudioTranscriptionsData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ChatAudioTranscriptionsResponse,
    PostV1ChatAudioTranscriptionsError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      'Content-Type': null,
    },
    url: '/v1/chat/audio/transcriptions',
  });
};

/**
 * 文字转音频
 */
export const postV1ChatAudioSpeech = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ChatAudioSpeechData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ChatAudioSpeechResponse,
    PostV1ChatAudioSpeechError
  >({
    ...options,
    url: '/v1/chat/audio/speech',
  });
};

/**
 * agent聊天记录
 * 该agent在本系统调试端、用户端、api调用产生的数据
 */
export const getV1ChatAgentChat = <ThrowOnError extends boolean = false>(
  options: Options<GetV1ChatAgentChatData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1ChatAgentChatResponse, GetV1ChatAgentChatError>({
    ...options,
    url: '/v1/chat/agentChat',
  });
};

/**
 * 发送会话消息
 */
export const postV1ChatStreamBySessionId = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ChatStreamBySessionIdData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ChatStreamBySessionIdResponse,
    PostV1ChatStreamBySessionIdError
  >({
    ...options,
    url: '/v1/chat/stream/{sessionId}',
  });
};

/**
 * 停止执行
 */
export const postV1ChatStop = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ChatStopData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1ChatStopResponse, PostV1ChatStopError>({
    ...options,
    url: '/v1/chat/stop',
  });
};

/**
 * 音频转文字-流式
 */
export const postV1ChatAudioTranscriptionsStream = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ChatAudioTranscriptionsStreamData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ChatAudioTranscriptionsStreamResponse,
    PostV1ChatAudioTranscriptionsStreamError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      'Content-Type': null,
    },
    url: '/v1/chat/audio/transcriptions/stream',
  });
};

/**
 * 文字转音频-流式
 */
export const postV1ChatAudioSpeechStream = <ThrowOnError extends boolean = false>(
  options: Options<PostV1ChatAudioSpeechStreamData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1ChatAudioSpeechStreamResponse,
    PostV1ChatAudioSpeechStreamError
  >({
    ...options,
    url: '/v1/chat/audio/speech/stream',
  });
};

/**
 * 获取当前用户的信息
 */
export const getV1UserInfo = <ThrowOnError extends boolean = false>(
  options: Options<GetV1UserInfoData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1UserInfoResponse, GetV1UserInfoError>({
    ...options,
    url: '/v1/user/info',
  });
};

/**
 * 修改用户信息
 */
export const putV1UserUpdate = <ThrowOnError extends boolean = false>(
  options: Options<PutV1UserUpdateData, ThrowOnError>
) => {
  return (options?.client ?? client).put<ThrowOnError, PutV1UserUpdateResponse, PutV1UserUpdateError>({
    ...options,
    url: '/v1/user/update',
  });
};

/**
 * 修改密码
 */
export const putV1UserUpdatePwd = <ThrowOnError extends boolean = false>(
  options: Options<PutV1UserUpdatePwdData, ThrowOnError>
) => {
  return (options?.client ?? client).put<ThrowOnError, PutV1UserUpdatePwdResponse, PutV1UserUpdatePwdError>({
    ...options,
    url: '/v1/user/updatePwd',
  });
};

/**
 * 重置密码-验证邮箱
 */
export const postV1UserResetPwdCaptcha = <ThrowOnError extends boolean = false>(
  options: Options<PostV1UserResetPwdCaptchaData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1UserResetPwdCaptchaResponse,
    PostV1UserResetPwdCaptchaError
  >({
    ...options,
    url: '/v1/user/resetPwd/captcha',
  });
};

/**
 * 重置密码-检查验证码
 */
export const postV1UserResetPwdCaptchaVerify = <ThrowOnError extends boolean = false>(
  options: Options<PostV1UserResetPwdCaptchaVerifyData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1UserResetPwdCaptchaVerifyResponse,
    PostV1UserResetPwdCaptchaVerifyError
  >({
    ...options,
    url: '/v1/user/resetPwd/captcha/verify',
  });
};

/**
 * 重置密码-验证链接
 */
export const getV1UserResetPwdByUuid = <ThrowOnError extends boolean = false>(
  options: Options<GetV1UserResetPwdByUuidData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1UserResetPwdByUuidResponse,
    GetV1UserResetPwdByUuidError
  >({
    ...options,
    url: '/v1/user/resetPwd/{uuid}',
  });
};

/**
 * 重置密码
 */
export const postV1UserResetPwdByUuid = <ThrowOnError extends boolean = false>(
  options: Options<PostV1UserResetPwdByUuidData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1UserResetPwdByUuidResponse,
    PostV1UserResetPwdByUuidError
  >({
    ...options,
    url: '/v1/user/resetPwd/{uuid}',
  });
};

/**
 * 重置密码
 */
export const postV1UserResetPwdConfirm = <ThrowOnError extends boolean = false>(
  options: Options<PostV1UserResetPwdConfirmData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1UserResetPwdConfirmResponse,
    PostV1UserResetPwdConfirmError
  >({
    ...options,
    url: '/v1/user/resetPwd/confirm',
  });
};

/**
 * @deprecated
 * 文件上传
 */
export const postV1FileUpload = <ThrowOnError extends boolean = false>(
  options: Options<PostV1FileUploadData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1FileUploadResponse, PostV1FileUploadError>({
    ...options,
    ...formDataBodySerializer,
    headers: {
      'Content-Type': null,
    },
    url: '/v1/file/upload',
  });
};

/**
 * @deprecated
 * 文件下载
 */
export const getV1FileDownload = <ThrowOnError extends boolean = false>(
  options: Options<GetV1FileDownloadData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1FileDownloadResponse, GetV1FileDownloadError>({
    ...options,
    url: '/v1/file/download',
  });
};

/**
 * 知识库上传文件
 */
export const postV1FileDatasetUpload = <ThrowOnError extends boolean = false>(
  options: Options<PostV1FileDatasetUploadData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1FileDatasetUploadResponse,
    PostV1FileDatasetUploadError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      'Content-Type': null,
    },
    url: '/v1/file/dataset/upload',
  });
};

/**
 * 知识库下载原文件(用户上传的文件)
 */
export const getV1FileDatasetFileDownload = <ThrowOnError extends boolean = false>(
  options: Options<GetV1FileDatasetFileDownloadData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1FileDatasetFileDownloadResponse,
    GetV1FileDatasetFileDownloadError
  >({
    ...options,
    url: '/v1/file/dataset/file/download',
  });
};

/**
 * 下载知识库markdown文件(转换后的markdown文件及资源)
 */
export const getV1FileDatasetMarkdownDownload = <ThrowOnError extends boolean = false>(
  options: Options<GetV1FileDatasetMarkdownDownloadData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1FileDatasetMarkdownDownloadResponse,
    GetV1FileDatasetMarkdownDownloadError
  >({
    ...options,
    url: '/v1/file/dataset/markdown/download',
  });
};

/**
 * 查询异步markdown转换进度。
 */
export const getV1FileDatasetMarkdownProgress = <ThrowOnError extends boolean = false>(
  options: Options<GetV1FileDatasetMarkdownProgressData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1FileDatasetMarkdownProgressResponse,
    GetV1FileDatasetMarkdownProgressError
  >({
    ...options,
    url: '/v1/file/dataset/markdown/progress',
  });
};

/**
 * 预览markdown文件内容
 */
export const getV1FileDatasetMarkdownPreview = <ThrowOnError extends boolean = false>(
  options: Options<GetV1FileDatasetMarkdownPreviewData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1FileDatasetMarkdownPreviewResponse,
    GetV1FileDatasetMarkdownPreviewError
  >({
    ...options,
    url: '/v1/file/dataset/markdown/preview',
  });
};

/**
 * 知识库Markdown图片资源
 */
export const getV1FileDatasetImagesByFilename = <ThrowOnError extends boolean = false>(
  options: Options<GetV1FileDatasetImagesByFilenameData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1FileDatasetImagesByFilenameResponse,
    GetV1FileDatasetImagesByFilenameError
  >({
    ...options,
    url: '/v1/file/dataset/images/{filename}',
  });
};

/**
 * 删除文件
 */
export const deleteV1FileById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1FileByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<ThrowOnError, DeleteV1FileByIdResponse, DeleteV1FileByIdError>({
    ...options,
    url: '/v1/file/{id}',
  });
};

/**
 * 知识库Markdown图片资源
 */
export const getV1FileDatasetImagesByFileIdByFilename = <ThrowOnError extends boolean = false>(
  options: Options<GetV1FileDatasetImagesByFileIdByFilenameData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1FileDatasetImagesByFileIdByFilenameResponse,
    GetV1FileDatasetImagesByFileIdByFilenameError
  >({
    ...options,
    url: '/v1/file/dataset/images/{fileId}/{filename}',
  });
};

/**
 * Chat临时文件上传
 */
export const postV1FileChatUpload = <ThrowOnError extends boolean = false>(
  options: Options<PostV1FileChatUploadData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1FileChatUploadResponse,
    PostV1FileChatUploadError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      'Content-Type': null,
    },
    url: '/v1/file/chat/upload',
  });
};

/**
 * 生成文件访问url
 */
export const getV1FileResourceGenerateUrl = <ThrowOnError extends boolean = false>(
  options: Options<GetV1FileResourceGenerateUrlData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1FileResourceGenerateUrlResponse,
    GetV1FileResourceGenerateUrlError
  >({
    ...options,
    url: '/v1/file/resource/generateUrl',
  });
};

/**
 * 本地文件下载
 */
export const getV1FileResourceDownload = <ThrowOnError extends boolean = false>(
  options: Options<GetV1FileResourceDownloadData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1FileResourceDownloadResponse,
    GetV1FileResourceDownloadError
  >({
    ...options,
    url: '/v1/file/resource/download',
  });
};

/**
 * 创建一个新的知识库。
 */
export const postV1DatasetAdd = <ThrowOnError extends boolean = false>(
  options: Options<PostV1DatasetAddData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1DatasetAddResponse, PostV1DatasetAddError>({
    ...options,
    url: '/v1/dataset/add',
  });
};

/**
 * 通过ID获取知识库。
 */
export const getV1DatasetById = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1DatasetByIdResponse, GetV1DatasetByIdError>({
    ...options,
    url: '/v1/dataset/{id}',
  });
};

/**
 * 更新现有知识库。
 */
export const putV1DatasetById = <ThrowOnError extends boolean = false>(
  options: Options<PutV1DatasetByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).put<ThrowOnError, PutV1DatasetByIdResponse, PutV1DatasetByIdError>({
    ...options,
    url: '/v1/dataset/{id}',
  });
};

/**
 * 通过ID删除知识库。
 */
export const deleteV1DatasetById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1DatasetByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteV1DatasetByIdResponse,
    DeleteV1DatasetByIdError
  >({
    ...options,
    url: '/v1/dataset/{id}',
  });
};

/**
 * List datasets associated with an agent.
 */
export const getV1DatasetListDatasetsByAgent = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetListDatasetsByAgentData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1DatasetListDatasetsByAgentResponse,
    GetV1DatasetListDatasetsByAgentError
  >({
    ...options,
    url: '/v1/dataset/listDatasetsByAgent',
  });
};

/**
 * 切换知识库共享状态。
 */
export const putV1DatasetByIdShare = <ThrowOnError extends boolean = false>(
  options: Options<PutV1DatasetByIdShareData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    PutV1DatasetByIdShareResponse,
    PutV1DatasetByIdShareError
  >({
    ...options,
    url: '/v1/dataset/{id}/share',
  });
};

/**
 * 检索记录
 */
export const getV1DatasetByIdRetrieveHistory = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetByIdRetrieveHistoryData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1DatasetByIdRetrieveHistoryResponse,
    GetV1DatasetByIdRetrieveHistoryError
  >({
    ...options,
    url: '/v1/dataset/{id}/retrieve/history',
  });
};

/**
 * 创建新文档。
 */
export const postV1DatasetByDatasetIdDocuments = <ThrowOnError extends boolean = false>(
  options: Options<PostV1DatasetByDatasetIdDocumentsData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1DatasetByDatasetIdDocumentsResponse,
    PostV1DatasetByDatasetIdDocumentsError
  >({
    ...options,
    url: '/v1/dataset/{datasetId}/documents',
  });
};

/**
 * 通过知识库ID获取文档。
 */
export const getV1DatasetByDatasetIdDocuments = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetByDatasetIdDocumentsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1DatasetByDatasetIdDocumentsResponse,
    GetV1DatasetByDatasetIdDocumentsError
  >({
    ...options,
    url: '/v1/dataset/{datasetId}/documents',
  });
};

/**
 * 重命名文档。
 */
export const putV1DatasetDocumentsByDocumentIdRename = <ThrowOnError extends boolean = false>(
  options: Options<PutV1DatasetDocumentsByDocumentIdRenameData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    PutV1DatasetDocumentsByDocumentIdRenameResponse,
    PutV1DatasetDocumentsByDocumentIdRenameError
  >({
    ...options,
    url: '/v1/dataset/documents/{documentId}/rename',
  });
};

/**
 * 通过ID删除文档。
 */
export const deleteV1DatasetDocumentsByDocumentId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1DatasetDocumentsByDocumentIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteV1DatasetDocumentsByDocumentIdResponse,
    DeleteV1DatasetDocumentsByDocumentIdError
  >({
    ...options,
    url: '/v1/dataset/documents/{documentId}',
  });
};

/**
 * 批量删除文档。
 */
export const deleteV1DatasetDocumentsBatchDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1DatasetDocumentsBatchDeleteData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteV1DatasetDocumentsBatchDeleteResponse,
    DeleteV1DatasetDocumentsBatchDeleteError
  >({
    ...options,
    url: '/v1/dataset/documents/batchDelete',
  });
};

/**
 * 通过文档ID获取文档片段，带分页。
 */
export const getV1DatasetDocumentsByDocumentIdSegments = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetDocumentsByDocumentIdSegmentsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1DatasetDocumentsByDocumentIdSegmentsResponse,
    GetV1DatasetDocumentsByDocumentIdSegmentsError
  >({
    ...options,
    url: '/v1/dataset/documents/{documentId}/segments',
  });
};

/**
 * 创建新片段。
 */
export const postV1DatasetDocumentsByDocumentIdSegments = <ThrowOnError extends boolean = false>(
  options: Options<PostV1DatasetDocumentsByDocumentIdSegmentsData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1DatasetDocumentsByDocumentIdSegmentsResponse,
    PostV1DatasetDocumentsByDocumentIdSegmentsError
  >({
    ...options,
    url: '/v1/dataset/documents/{documentId}/segments',
  });
};

/**
 * 切换文档启用状态。
 */
export const putV1DatasetDocumentsByDocumentIdEnable = <ThrowOnError extends boolean = false>(
  options: Options<PutV1DatasetDocumentsByDocumentIdEnableData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    PutV1DatasetDocumentsByDocumentIdEnableResponse,
    PutV1DatasetDocumentsByDocumentIdEnableError
  >({
    ...options,
    url: '/v1/dataset/documents/{documentId}/enable',
  });
};

/**
 * 切换片段启用状态。
 */
export const putV1DatasetSegmentsBySegmentIdEnable = <ThrowOnError extends boolean = false>(
  options: Options<PutV1DatasetSegmentsBySegmentIdEnableData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    PutV1DatasetSegmentsBySegmentIdEnableResponse,
    PutV1DatasetSegmentsBySegmentIdEnableError
  >({
    ...options,
    url: '/v1/dataset/segments/{segmentId}/enable',
  });
};

/**
 * 通过文本搜索片段内容。
 */
export const getV1DatasetDocumentsByDocumentIdSegmentsSearchByText = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetDocumentsByDocumentIdSegmentsSearchByTextData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1DatasetDocumentsByDocumentIdSegmentsSearchByTextResponse,
    GetV1DatasetDocumentsByDocumentIdSegmentsSearchByTextError
  >({
    ...options,
    url: '/v1/dataset/documents/{documentId}/segments/searchByText',
  });
};

/**
 * 通过ID更新片段。
 */
export const putV1DatasetSegmentsBySegmentId = <ThrowOnError extends boolean = false>(
  options: Options<PutV1DatasetSegmentsBySegmentIdData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    PutV1DatasetSegmentsBySegmentIdResponse,
    PutV1DatasetSegmentsBySegmentIdError
  >({
    ...options,
    url: '/v1/dataset/segments/{segmentId}',
  });
};

/**
 * 通过ID删除片段。
 */
export const deleteV1DatasetSegmentsBySegmentId = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1DatasetSegmentsBySegmentIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteV1DatasetSegmentsBySegmentIdResponse,
    DeleteV1DatasetSegmentsBySegmentIdError
  >({
    ...options,
    url: '/v1/dataset/segments/{segmentId}',
  });
};

/**
 * 召回测试
 */
export const getV1DatasetByIdRetrieve = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetByIdRetrieveData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1DatasetByIdRetrieveResponse,
    GetV1DatasetByIdRetrieveError
  >({
    ...options,
    url: '/v1/dataset/{id}/retrieve',
  });
};

/**
 * 生成API Key
 */
export const getV1DatasetByIdApiKeyGenerate = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetByIdApiKeyGenerateData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1DatasetByIdApiKeyGenerateResponse,
    GetV1DatasetByIdApiKeyGenerateError
  >({
    ...options,
    url: '/v1/dataset/{id}/apiKey/generate',
  });
};

/**
 * 预览将文档分割为片段。
 */
export const postV1DatasetDocumentsSplit = <ThrowOnError extends boolean = false>(
  options: Options<PostV1DatasetDocumentsSplitData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1DatasetDocumentsSplitResponse,
    PostV1DatasetDocumentsSplitError
  >({
    ...options,
    url: '/v1/dataset/documents/split',
  });
};

/**
 * 批量删除片段。
 */
export const deleteV1DatasetSegmentsBatchDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1DatasetSegmentsBatchDeleteData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteV1DatasetSegmentsBatchDeleteResponse,
    DeleteV1DatasetSegmentsBatchDeleteError
  >({
    ...options,
    url: '/v1/dataset/segments/batchDelete',
  });
};

/**
 * 获取知识库的分页列表。
 */
export const getV1DatasetList = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetListData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1DatasetListResponse, GetV1DatasetListError>({
    ...options,
    url: '/v1/dataset/list',
  });
};

/**
 * retrieveExternal
 */
export const getV1DatasetByIdRetrieveExternal = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetByIdRetrieveExternalData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1DatasetByIdRetrieveExternalResponse,
    GetV1DatasetByIdRetrieveExternalError
  >({
    ...options,
    url: '/v1/dataset/{id}/retrieve/external',
  });
};

/**
 * 检索记录 片段详情
 */
export const getV1DatasetRetrieveHistoryById = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetRetrieveHistoryByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1DatasetRetrieveHistoryByIdResponse,
    GetV1DatasetRetrieveHistoryByIdError
  >({
    ...options,
    url: '/v1/dataset/retrieve/history/{id}',
  });
};

/**
 * 知识库检索(desktop端)
 */
export const getV1DatasetRetrieveDesktop = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetRetrieveDesktopData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1DatasetRetrieveDesktopResponse,
    GetV1DatasetRetrieveDesktopError
  >({
    ...options,
    url: '/v1/dataset/retrieveDesktop',
  });
};

/**
 * 知识库文档更新摘要
 */
export const putV1DatasetDocumentSummary = <ThrowOnError extends boolean = false>(
  options: Options<PutV1DatasetDocumentSummaryData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    PutV1DatasetDocumentSummaryResponse,
    PutV1DatasetDocumentSummaryError
  >({
    ...options,
    url: '/v1/dataset/document/summary',
  });
};

/**
 * 查看文档摘要
 */
export const getV1DatasetDocumentsByDocumentIdSummary = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetDocumentsByDocumentIdSummaryData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1DatasetDocumentsByDocumentIdSummaryResponse,
    GetV1DatasetDocumentsByDocumentIdSummaryError
  >({
    ...options,
    url: '/v1/dataset/documents/{documentId}/summary',
  });
};

/**
 * 文档信息
 */
export const getV1DatasetDocumentsInfoByDocumentId = <ThrowOnError extends boolean = false>(
  options: Options<GetV1DatasetDocumentsInfoByDocumentIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1DatasetDocumentsInfoByDocumentIdResponse,
    GetV1DatasetDocumentsInfoByDocumentIdError
  >({
    ...options,
    url: '/v1/dataset/documentsInfo/{documentId}',
  });
};

/**
 * 积分充值列表
 */
export const getV1PointsRecharges = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PointsRechargesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1PointsRechargesResponse,
    GetV1PointsRechargesError
  >({
    ...options,
    url: '/v1/points/recharges',
  });
};

/**
 * 积分消耗列表
 */
export const getV1PointsUsages = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PointsUsagesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1PointsUsagesResponse, GetV1PointsUsagesError>({
    ...options,
    url: '/v1/points/usages',
  });
};

/**
 * 查询积分余额
 */
export const getV1PointsBalance = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PointsBalanceData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1PointsBalanceResponse, GetV1PointsBalanceError>({
    ...options,
    url: '/v1/points/balance',
  });
};

/**
 * 积分策略配置
 */
export const getV1PointsStrategy = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PointsStrategyData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1PointsStrategyResponse, GetV1PointsStrategyError>(
    {
      ...options,
      url: '/v1/points/strategy',
    }
  );
};

/**
 * 保存积分策略配置（JSON）
 */
export const putV1PointsStrategy = <ThrowOnError extends boolean = false>(
  options: Options<PutV1PointsStrategyData, ThrowOnError>
) => {
  return (options?.client ?? client).put<ThrowOnError, PutV1PointsStrategyResponse, PutV1PointsStrategyError>(
    {
      ...options,
      url: '/v1/points/strategy',
    }
  );
};

/**
 * 查询可用的活动
 */
export const getV1PointsActiveActivities = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PointsActiveActivitiesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1PointsActiveActivitiesResponse,
    GetV1PointsActiveActivitiesError
  >({
    ...options,
    url: '/v1/points/activeActivities',
  });
};

/**
 * 计算优惠数据
 */
export const getV1PointsCalculateDiscount = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PointsCalculateDiscountData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1PointsCalculateDiscountResponse,
    GetV1PointsCalculateDiscountError
  >({
    ...options,
    url: '/v1/points/calculateDiscount',
  });
};

/**
 * 当前账号是否已绑定手机号
 */
export const getV1RegisterHasBind = <ThrowOnError extends boolean = false>(
  options: Options<GetV1RegisterHasBindData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1RegisterHasBindResponse,
    GetV1RegisterHasBindError
  >({
    ...options,
    url: '/v1/register/hasBind',
  });
};

/**
 * 发送短信验证码
 */
export const postV1RegisterSendSms = <ThrowOnError extends boolean = false>(
  options: Options<PostV1RegisterSendSmsData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1RegisterSendSmsResponse,
    PostV1RegisterSendSmsError
  >({
    ...options,
    url: '/v1/register/sendSms',
  });
};

/**
 * 验证短信验证码
 */
export const postV1RegisterVerifyCode = <ThrowOnError extends boolean = false>(
  options: Options<PostV1RegisterVerifyCodeData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1RegisterVerifyCodeResponse,
    PostV1RegisterVerifyCodeError
  >({
    ...options,
    url: '/v1/register/verifyCode',
  });
};

/**
 * 绑定手机号
 */
export const postV1RegisterBind = <ThrowOnError extends boolean = false>(
  options: Options<PostV1RegisterBindData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1RegisterBindResponse, PostV1RegisterBindError>({
    ...options,
    url: '/v1/register/bind',
  });
};

/**
 * 换绑手机号
 */
export const postV1RegisterRebind = <ThrowOnError extends boolean = false>(
  options: Options<PostV1RegisterRebindData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1RegisterRebindResponse,
    PostV1RegisterRebindError
  >({
    ...options,
    url: '/v1/register/rebind',
  });
};

/**
 * 支付记录详情
 */
export const getV1PayPaymentById = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PayPaymentByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1PayPaymentByIdResponse, GetV1PayPaymentByIdError>(
    {
      ...options,
      url: '/v1/pay/payment/{id}',
    }
  );
};

/**
 * 微信native支付
 */
export const postV1PayWechatNative = <ThrowOnError extends boolean = false>(
  options: Options<PostV1PayWechatNativeData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1PayWechatNativeResponse,
    PostV1PayWechatNativeError
  >({
    ...options,
    url: '/v1/pay/wechat/native',
  });
};

/**
 * 支付宝网页支付
 */
export const postV1PayAlipayWeb = <ThrowOnError extends boolean = false>(
  options: Options<PostV1PayAlipayWebData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1PayAlipayWebResponse, PostV1PayAlipayWebError>({
    ...options,
    url: '/v1/pay/alipay/web',
  });
};

/**
 * 支付记录列表
 */
export const getV1PayPayments = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PayPaymentsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1PayPaymentsResponse, GetV1PayPaymentsError>({
    ...options,
    url: '/v1/pay/payments',
  });
};

/**
 * 可开发票金额查询
 */
export const getV1PayInvoiceAmount = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PayInvoiceAmountData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1PayInvoiceAmountResponse,
    GetV1PayInvoiceAmountError
  >({
    ...options,
    url: '/v1/pay/invoice/amount',
  });
};

/**
 * 发票申请
 */
export const postV1PayInvoiceApply = <ThrowOnError extends boolean = false>(
  options: Options<PostV1PayInvoiceApplyData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1PayInvoiceApplyResponse,
    PostV1PayInvoiceApplyError
  >({
    ...options,
    url: '/v1/pay/invoice/apply',
  });
};

/**
 * 发票记录列表
 */
export const getV1PayInvoiceList = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PayInvoiceListData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1PayInvoiceListResponse, GetV1PayInvoiceListError>(
    {
      ...options,
      url: '/v1/pay/invoice/list',
    }
  );
};

/**
 * 关闭支付订单
 */
export const postV1PayCloseOrder = <ThrowOnError extends boolean = false>(
  options: Options<PostV1PayCloseOrderData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1PayCloseOrderResponse,
    PostV1PayCloseOrderError
  >({
    ...options,
    url: '/v1/pay/closeOrder',
  });
};

/**
 * 插件列表
 * 智连中选择插件应只查已启用状态的插件
 */
export const getV1PluginList = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PluginListData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV1PluginListResponse, GetV1PluginListError>({
    ...options,
    url: '/v1/plugin/list',
  });
};

/**
 * 新增插件（系统管理员）
 */
export const postV1PluginAdd = <ThrowOnError extends boolean = false>(
  options: Options<PostV1PluginAddData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV1PluginAddResponse, PostV1PluginAddError>({
    ...options,
    ...formDataBodySerializer,
    headers: {
      'Content-Type': null,
    },
    url: '/v1/plugin/add',
  });
};

/**
 * 编辑插件（系统管理员）
 */
export const putV1PluginById = <ThrowOnError extends boolean = false>(
  options: Options<PutV1PluginByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).put<ThrowOnError, PutV1PluginByIdResponse, PutV1PluginByIdError>({
    ...options,
    url: '/v1/plugin/{id}',
  });
};

/**
 * 删除插件（系统管理员）
 */
export const deleteV1PluginById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1PluginByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteV1PluginByIdResponse,
    DeleteV1PluginByIdError
  >({
    ...options,
    url: '/v1/plugin/{id}',
  });
};

/**
 * 启用插件（系统管理员）
 */
export const postV1PluginByIdEnable = <ThrowOnError extends boolean = false>(
  options: Options<PostV1PluginByIdEnableData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1PluginByIdEnableResponse,
    PostV1PluginByIdEnableError
  >({
    ...options,
    url: '/v1/plugin/{id}/enable',
  });
};

/**
 * 关闭插件（系统管理员）
 */
export const postV1PluginByIdDisable = <ThrowOnError extends boolean = false>(
  options: Options<PostV1PluginByIdDisableData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1PluginByIdDisableResponse,
    PostV1PluginByIdDisableError
  >({
    ...options,
    url: '/v1/plugin/{id}/disable',
  });
};

/**
 * 智连列表
 */
export const getV1PluginConnector = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PluginConnectorData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1PluginConnectorResponse,
    GetV1PluginConnectorError
  >({
    ...options,
    url: '/v1/plugin/connector',
  });
};

/**
 * 新增智连
 */
export const postV1PluginConnector = <ThrowOnError extends boolean = false>(
  options: Options<PostV1PluginConnectorData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1PluginConnectorResponse,
    PostV1PluginConnectorError
  >({
    ...options,
    url: '/v1/plugin/connector',
  });
};

/**
 * 编辑智连
 */
export const putV1PluginConnectorById = <ThrowOnError extends boolean = false>(
  options: Options<PutV1PluginConnectorByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    ThrowOnError,
    PutV1PluginConnectorByIdResponse,
    PutV1PluginConnectorByIdError
  >({
    ...options,
    url: '/v1/plugin/connector/{id}',
  });
};

/**
 * 删除智连
 */
export const deleteV1PluginConnectorById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV1PluginConnectorByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    ThrowOnError,
    DeleteV1PluginConnectorByIdResponse,
    DeleteV1PluginConnectorByIdError
  >({
    ...options,
    url: '/v1/plugin/connector/{id}',
  });
};

/**
 * 获取插件配置 schema
 */
export const getV1PluginByPluginIdSchema = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PluginByPluginIdSchemaData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1PluginByPluginIdSchemaResponse,
    GetV1PluginByPluginIdSchemaError
  >({
    ...options,
    url: '/v1/plugin/{pluginId}/schema',
  });
};

/**
 * 智连配置回显数据
 */
export const getV1PluginConnectorByIdData = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PluginConnectorByIdDataData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1PluginConnectorByIdDataResponse,
    GetV1PluginConnectorByIdDataError
  >({
    ...options,
    url: '/v1/plugin/connector/{id}/data',
  });
};

/**
 * 设置智连上下线
 */
export const postV1PluginConnectorByIdStatus = <ThrowOnError extends boolean = false>(
  options: Options<PostV1PluginConnectorByIdStatusData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1PluginConnectorByIdStatusResponse,
    PostV1PluginConnectorByIdStatusError
  >({
    ...options,
    url: '/v1/plugin/connector/{id}/status',
  });
};

/**
 * 统计数据
 */
export const postV1PluginConnectorAnalyze = <ThrowOnError extends boolean = false>(
  options: Options<PostV1PluginConnectorAnalyzeData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1PluginConnectorAnalyzeResponse,
    PostV1PluginConnectorAnalyzeError
  >({
    ...options,
    url: '/v1/plugin/connector/analyze',
  });
};

/**
 * agent列表(智连)
 */
export const getV1PluginAgentList = <ThrowOnError extends boolean = false>(
  options: Options<GetV1PluginAgentListData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV1PluginAgentListResponse,
    GetV1PluginAgentListError
  >({
    ...options,
    url: '/v1/plugin/agentList',
  });
};

/**
 * 文件上传
 */
export const postV2FileUpload = <ThrowOnError extends boolean = false>(
  options: Options<PostV2FileUploadData, ThrowOnError>
) => {
  return (options?.client ?? client).post<ThrowOnError, PostV2FileUploadResponse, PostV2FileUploadError>({
    ...options,
    ...formDataBodySerializer,
    headers: {
      'Content-Type': null,
    },
    url: '/v2/file/upload',
  });
};

/**
 * 文件预览
 */
export const getV2FilePreview = <ThrowOnError extends boolean = false>(
  options: Options<GetV2FilePreviewData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV2FilePreviewResponse, GetV2FilePreviewError>({
    ...options,
    url: '/v2/file/preview',
  });
};

/**
 * 删除文件
 */
export const deleteV2FileById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteV2FileByIdData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<ThrowOnError, DeleteV2FileByIdResponse, DeleteV2FileByIdError>({
    ...options,
    url: '/v2/file/{id}',
  });
};

/**
 * 文件下载
 */
export const getV2FileDownload = <ThrowOnError extends boolean = false>(
  options: Options<GetV2FileDownloadData, ThrowOnError>
) => {
  return (options?.client ?? client).get<ThrowOnError, GetV2FileDownloadResponse, GetV2FileDownloadError>({
    ...options,
    url: '/v2/file/download',
  });
};

/**
 * 下载markdown zip
 */
export const getV2FileDownloadMarkdown = <ThrowOnError extends boolean = false>(
  options: Options<GetV2FileDownloadMarkdownData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV2FileDownloadMarkdownResponse,
    GetV2FileDownloadMarkdownError
  >({
    ...options,
    url: '/v2/file/download/markdown',
  });
};

/**
 * 查询异步markdown转换进度
 */
export const getV2FileMarkdownProgress = <ThrowOnError extends boolean = false>(
  options: Options<GetV2FileMarkdownProgressData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV2FileMarkdownProgressResponse,
    GetV2FileMarkdownProgressError
  >({
    ...options,
    url: '/v2/file/markdown/progress',
  });
};

/**
 * 预览markdown文件内容
 */
export const getV2FileMarkdownPreview = <ThrowOnError extends boolean = false>(
  options: Options<GetV2FileMarkdownPreviewData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ThrowOnError,
    GetV2FileMarkdownPreviewResponse,
    GetV2FileMarkdownPreviewError
  >({
    ...options,
    url: '/v2/file/markdown/preview',
  });
};

/**
 * 模拟支付成功回调
 * 只适用于测试环境
 */
export const postV1NotifyMockNotify = <ThrowOnError extends boolean = false>(
  options: Options<PostV1NotifyMockNotifyData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    ThrowOnError,
    PostV1NotifyMockNotifyResponse,
    PostV1NotifyMockNotifyError
  >({
    ...options,
    url: '/v1/notify/mockNotify',
  });
};
